In [1]:
# 数据处理
import pandas as pd
import numpy as np
 
# 绘图
import seaborn as sns
import matplotlib.pyplot as plt

In [19]:
## 读取数据
df = pd.read_csv("problem2PCA.csv",encoding="gb2312")
df.head()


类型  二氧化硅(SiO2)  氧化钠(Na2O)  氧化钾(K2O)  氧化钙(CaO)  氧化镁(MgO)  氧化铝(Al2O3)  \
0  高钾       69.33        0.0      9.99      6.32      0.87        3.93   
1  铅钡       36.28        0.0      1.05      2.34      1.18        5.73   
2  高钾       87.05        0.0      5.19      2.01      0.00        4.06   
3  高钾       61.71        0.0     12.37      5.87      1.11        5.50   
4  高钾       65.88        0.0      9.67      7.12      1.56        6.44   

   氧化铁(Fe2O3)  氧化铜(CuO)  氧化铅(PbO)  氧化钡(BaO)  五氧化二磷(P2O5)  氧化锶(SrO)  氧化锡(SnO2)  \
0        1.74      3.87      0.00      0.00         1.17      0.00        0.0   
1        1.86      0.26     47.43      0.00         3.57      0.19        0.0   
2        0.00      0.78      0.25      0.00         0.66      0.00        0.0   
3        2.16      5.09      1.41      2.86         0.70      0.10        0.0   
4        2.06      2.18      0.00      0.00         0.79      0.00        0.0   

   二氧化硫(SO2)     sum  
0       0.39   97.22  
1       0.00   99.89  
2       0.00  100.00  
3       0.00   98.88  
4       0.36   95.70

In [22]:
## labelencoder
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
df["类型"] = LabelEncoder().fit_transform(np.array(df["类型"])).reshape(-1,1)

In [25]:
# 数据归一化
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
df = mms.fit_transform(df)
df


array([[1.        , 0.67472736, 0.        , ..., 0.        , 0.10655738,
        0.76013805],
       [0.        , 0.28295401, 0.        , ..., 0.        , 0.        ,
        0.99050906],
       [1.        , 0.88477952, 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.        , 0.19843528, 0.        , ..., 0.        , 0.        ,
        0.33045729],
       [0.        , 0.15422001, 0.        , ..., 0.        , 0.        ,
        0.35030198],
       [0.        , 0.21313419, 0.        , ..., 0.        , 0.        ,
        0.89301122]])

In [33]:
# PCA降维
from sklearn.decomposition import PCA
from sklearn import preprocessing
pca = PCA()
pca.fit(df)

PCA()

In [34]:
pca.components_ # 模型的各个特征向量

array([[ 6.67745141e-01,  3.24439901e-01,  1.99798476e-02,
         3.38839717e-01,  1.55479525e-01,  5.06047187e-02,
         1.49835486e-01,  1.05445225e-01,  1.98893176e-02,
        -3.88445025e-01, -1.89764277e-01, -1.42629538e-01,
        -2.27761229e-01,  2.86313716e-02, -3.11190835e-02,
         1.09715183e-01],
       [ 1.16575931e-01, -3.91355360e-01, -1.32542728e-01,
         2.52298373e-01,  5.09376252e-01,  3.39766011e-01,
         1.81228142e-01,  2.53701363e-01,  5.94959473e-02,
         1.96252242e-01, -4.80050054e-02,  4.11951348e-01,
         1.78271616e-01,  4.39252703e-03, -3.41191185e-02,
        -1.81352085e-01],
       [ 4.79410366e-01, -2.42178725e-01, -7.99465198e-03,
         1.94388731e-02, -8.29312991e-02, -3.41427011e-01,
        -2.71406921e-01, -1.40655722e-01,  4.74281987e-01,
         7.94369755e-02,  4.15411330e-01,  3.41733694e-02,
         1.31389240e-01, -7.26137826e-02,  1.89020393e-01,
        -1.75855047e-01],
       [ 4.36807461e-01,  4.02926205e

In [35]:
pca.explained_variance_  # 贡献方差，即特征根

array([3.84033384e-01, 1.56577202e-01, 1.20999565e-01, 6.24691956e-02,
       5.64111088e-02, 5.29760073e-02, 4.31386269e-02, 2.93195767e-02,
       2.72336689e-02, 2.10011162e-02, 1.57163555e-02, 1.44629846e-02,
       1.28859136e-02, 1.04951153e-02, 5.47223731e-03, 4.39894745e-33])

In [36]:
pca.explained_variance_ratio_ #各个成分各自的方差百分比（贡献率）

array([3.79033157e-01, 1.54538521e-01, 1.19424115e-01, 6.16558284e-02,
       5.56766197e-02, 5.22862442e-02, 4.25769493e-02, 2.89378273e-02,
       2.68790786e-02, 2.07276756e-02, 1.55117240e-02, 1.42746723e-02,
       1.27181352e-02, 1.03584658e-02, 5.40098718e-03, 4.34167187e-33])

In [38]:
## 假设我们就取3个主成分
pca = PCA(3) #确定3个主成分
pca.fit(df)
low_d = pca.transform(df)# low_d降维后的结果
low_d
# https://zhuanlan.zhihu.com/p/452381311

array([[ 1.04561394,  0.29754061,  0.17105235],
       [-0.30520918,  0.18735651, -0.40512415],
       [ 0.90720708, -0.3715087 ,  0.09970363],
       [ 1.07362758,  0.40232053,  0.18837262],
       [ 1.07114975,  0.49036171, -0.02512586],
       [ 1.10431522,  0.62321863, -0.01644447],
       [ 0.92974407,  0.22257929, -0.13119721],
       [ 1.04567121,  0.70027818, -0.20884211],
       [ 0.77496119, -0.54622557,  0.23691043],
       [-0.65361043, -0.08374541,  0.95578454],
       [ 0.78548525, -0.59390709,  0.16700962],
       [ 0.78861589, -0.64429728,  0.14438682],
       [-0.48131585,  0.28883996,  0.22806281],
       [ 0.79556622, -0.57893976,  0.17371535],
       [ 1.15541097,  0.44673394,  0.22192039],
       [ 1.16196432,  0.34707832, -0.0765468 ],
       [ 1.18263112,  0.34670322,  0.03702275],
       [ 0.93948625, -0.12935735, -0.08156344],
       [ 0.21589921,  0.39563916,  0.45404829],
       [ 0.27478371,  0.08754709,  0.87442442],
       [ 0.18419588, -0.04367785, -0.470